[[redirects]]
  from = "/staff"
  to = "https://161.33.208.191.sslip.io/staff"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://161.33.208.191.sslip.io/api/:splat"
  status = 200
  force = true
